export const searchItems = [
  {
    title: "о нас",
    description: "и мерч, и маскоты, и ещё и мы",
    url: "/pages/about.html",
    type: "страница",
  },

  {
    title: "все статьи",
    description: "каталог статей про мемы!",
    url: "/pages/articles.html",
    type: "страница",
  },

  {
    title: "создать мем",
    description: "конструктор мемов, чтобы сделать свой прикол",
    url: "/pages/constructor.html",
    type: "страница",
  },

  {
    title: "рандом мем",
    description: "тут можно развить мемную насмотренность",
    url: "/pages/random.html",
    type: "страница",
  },

  {
    title: "Кто ты?",
    description: "тест на определение личности по знанию мемов",
    url: "/pages/tests/test1.html",
    type: "тест",
  },

  {
    title: "пазл",
    description: "мем рассыпался, теперь собирать пазл можно!",
    url: "/pages/tests/test2.html",
    type: "тест",
  },

  {
    title: "угадай мем",
    description: "мем в блюре, нужно разобраться, что ж там за картинка",
    url: "/pages/tests/test3.html",
    type: "тест",
  },

  {
    title: "нишевость",
    description: "давайте разбираться, что это и откуда взялось",
    url: "/pages/articles/art_1.html",
    type: "статья",
  },
  {
    title: "7 × 7 = 49",
    description: "почему интернет влюбился в цифры?",
    url: "/pages/articles/art_2.html",
    type: "статья",
  },
  {
    title: "CHINAMAXXING? Что?",
    description: "Почему интерес к Китаю всё не утихает?",
    url: "/pages/articles/art_3.html",
    type: "статья",
  },
  {
    title: "2026 is new 2016",
    description: "Почему все массово снимают бэк ту скул и вайны?",
    url: "/pages/articles/art_4.html",
    type: "статья",
  },
  {
    title: "морковка пять рублей",
    description: "ура! узнаём рецепт дешёвой пищи",
    url: "/pages/articles/art_5.html",
    type: "статья",
  },
  {
    title: "Сок любимый",
    description: "почему в любом соке внезапно находится яблоко",
    url: "/pages/articles/art_6.html",
    type: "статья",
  },
  {
    title: "кто это вообще?",
    description: "а он сейчас с нами в одной комнате",
    url: "/pages/articles/art_7.html",
    type: "статья",
  },
  {
    title: "ИИ-вечеринка",
    description: "поговорим про ии мемы",
    url: "/pages/articles/art_8.html",
    type: "статья",
  },
  {
    title: "рейджкомиксы",
    description: "как рейджкомиксы захватили интернет и подарили нам Trollface",
    url: "/pages/articles/art_9.html",
    type: "статья",
  },
  {
    title: "bogos binted?",
    description: "инопланетная бессмысленная переписка с пришельцем как мем",
    url: "/pages/articles/art_10.html",
    type: "статья",
  },
  {
    title: "DID YOU GUYS SEE THAT?",
    description: "как бегущий скелет превратился в коллективную галлюцинацию",
    url: "/pages/articles/art_11.html",
    type: "статья",
  },
  {
    title: "Не могу доказать",
    description: "что он знает? что он кому доказать пытается?",
    url: "/pages/articles/art_12.html",
    type: "статья",
  },
  {
    title: "ох зря я туда полез",
    description: "как криповые страшилки превратились в мем",
    url: "/pages/articles/art_13.html",
    type: "статья",
  },
  {
    title: "+1000 aura",
    description: "что за аура? давайте узнаем, что это за статы",
    url: "/pages/articles/art_14.html",
    type: "статья",
  },
  {
    title: "son",
    description: "мем son как реакция абсолютно на всё, вот круто",
    url: "/pages/articles/art_15.html",
    type: "статья",
  },
  {
    title: "демотиваторы",
    description: "как демотиваторы стали легендой мемной культуры",
    url: "/pages/articles/art_16.html",
    type: "статья",
  },
  {
    title: "тотя",
    description: "что такое тотя и почему с этого смеются по итогу",
    url: "/pages/articles/art_17.html",
    type: "статья",
  },
  {
    title: "delulu",
    description: "почему немного жить в фантазиях — это нормально",
    url: "/pages/articles/art_18.html",
    type: "статья",
  },
  {
    title: "better call saul",
    description: "почему лучше звонить солу, и как адвокат из сериала стал мемом",
    url: "/pages/articles/art_19.html",
    type: "статья",
  },
  {
    title: "bakamitai",
    description: "bakamitai, dame da ne или как грустная песня из игры превратилась мем",
    url: "/pages/articles/art_20.html",
    type: "статья",
  },
  {
    title: "плачущий купер",
    description: "как одна из самых грустных сцен «Интерстеллара» стала мемом",
    url: "/pages/articles/art_21.html",
    type: "статья",
  },
  {
    title: "Данил Колбасенко",
    description: "подскажите!! кто такой данил колбасенко",
    url: "/pages/articles/art_22.html",
    type: "статья",
  },
  {
    title: "nyan nyan nyan",
    description: "разбираемся, почему nyan cat — это отец брейнротов",
    url: "/pages/articles/art_23.html",
    type: "статья",
  },
  {
    title: "Дензел бьёт по столу",
    description: "Давайте разбираться, зачем он бьёт по столу",
    url: "/pages/articles/art_24.html",
    type: "статья",
  },
  {
    title: "собака и яблоко",
    description: "у этой собаки с яблоком в жизни творится тотальный экшн... надо разобраться",
    url: "/pages/articles/art_25.html",
    type: "статья",
  },
  {
    title: "думскроллинг",
    description: "что такое думскроллинг и почему так сложно остановиться",
    url: "/pages/articles/art_26.html",
    type: "статья",
  },
  {
    title: "хомяк",
    description: "как криво нарисованный хомяк стал универсальной эмоцией интернета",
    url: "/pages/articles/art_27.html",
    type: "статья",
  },
  {
    title: "гора эверест",
    description: "как кавер на песню из «Эйфории» превратился в мем",
    url: "/pages/articles/art_28.html",
    type: "статья",
  },
  {
    title: "Райан Гослинг",
    description: "Как Райан Гослинг стал мемом (да не умер он в конце «Драйва»!!)",
    url: "/pages/articles/art_29.html",
    type: "статья",
  },
  {
    title: "муся, это ты?",
    description: "кто такая муся?",
    url: "/pages/articles/art_30.html",
    type: "статья",
  },
  {
    title: "ishowspeed",
    description: "как стримерские реакции ishowspeed стали отдельным мемом",
    url: "/pages/articles/art_31.html",
    type: "статья",
  },
  {
    title: "рикролл",
    description: "история самого известного троллинга",
    url: "/pages/articles/art_32.html",
    type: "статья",
  },
  {
    title: "POV форматы",
    description: "пов три буквы стали отдельным жанром тиктока",
    url: "/pages/articles/art_33.html",
    type: "статья",
  },
  {
    title: "хоумлендер вздыхает",
    description: "как кадр из «Пацанов» стал универсальной реакцией",
    url: "/pages/articles/art_34.html",
    type: "статья",
  },
  {
    title: "жизненный цикл мемов",
    description: "почему раньше мемы жили годами, а сейчас умирают за неделю",
    url: "/pages/articles/art_35.html",
    type: "статья",
  },
  {
    title: "возьми телефон детка",
    description: "как фрагмент стрима Toxi$ превратился в мем",
    url: "/pages/articles/art_36.html",
    type: "статья",
  },
  {
    title: "не спеша",
    description: "пародия на ностальгические видео, которая превратилась в  брейнрот",
    url: "/pages/articles/art_37.html",
    type: "статья",
  },
  {
    title: "main character syndrome",
    description: "почему люди в интернете называют других главными героями?",
    url: "/pages/articles/art_38.html",
    type: "статья",
  },
  {
    title: "caramelldansen",
    description: "как шведская песня начала нулевых получила вторую жизнь в эпоху карантина",
    url: "/pages/articles/art_39.html",
    type: "статья",
  },
  {
    title: "сигма",
    description: "как герой «Американского психопата» стал мемом про ауру. а ещё и эдиты",
    url: "/pages/articles/art_40.html",
    type: "статья",
  },
  {
    title: "tiredcore",
    description: "почему усталость внезапно стала красивой",
    url: "/pages/articles/art_41.html",
    type: "статья",
  },
  {
    title: "real or cake?",
    description: "почему в какой-то момент интернет перестал доверять даже торту",
    url: "/pages/articles/art_42.html",
    type: "статья",
  },
  {
    title: "67",
    description: "67, оно же six seven, ща узнаем откуда оно взялось",
    url: "/pages/articles/art_43.html",
    type: "статья",
  },
  {
    title: "я тайлер дерден",
    description: "как Тайлер Дерден стал главным героем эдитов",
    url: "/pages/articles/art_44.html",
    type: "статья",
  },
  {
    title: "дикий огурец",
    description: "разбираемся, что там за дикий огурец",
    url: "/pages/articles/art_45.html",
    type: "статья",
  },
  {
    title: "still water",
    description: "почему стоячая вода внезапно стала мемом",
    url: "/pages/articles/art_46.html",
    type: "статья",
  },
  {
    title: "fake nostalgia",
    description: "почему тикток грустит по воспоминаниям, которых никогда не существовало",
    url: "/pages/articles/art_47.html",
    type: "статья",
  },
  {
    title: "большой шлёпа",
    description: "как домашний каракал Гоша стал легендой, Big Russian Floppa или просто Шлёпой :)",
    url: "/pages/articles/art_48.html",
    type: "статья",
  },
  {
    title: "Окак",
    description: "Что за кот в капюшоне? Что такое окак??",
    url: "/pages/articles/art_49.html",
    type: "статья",
  },
  {
    title: "умный человек скачать обои",
    description: "что это было? какой умный человек?",
    url: "/pages/articles/art_50.html",
    type: "статья",
  },
  {
    title: "смажьте мясо маслом",
    description: "Зачем мазать мясо маслом?",
    url: "/pages/articles/art_51.html",
    type: "статья",
  },
  {
    title: "Тун Тун Тун Сахур",
    description: "что это такое? у него дубинка, он опасен?",
    url: "/pages/articles/art_52.html",
    type: "статья",
  },
  {
    title: "фа ватафа",
    description: "давайте разбираться фа что значат эти слова пепе",
    url: "/pages/articles/art_53.html",
    type: "статья",
  },
  {
    title: "Грустный хомяк",
    description: "кто ж его так расстроил? разбираемся, что, почему и откуда!",
    url: "/pages/articles/art_54.html",
    type: "статья",
  },
];
